language: c
addons:
  apt:
    sources:
      - sourceline: 'ppa:keithw/glfw3'
    packages:
      - libc6-dev-i386
      - linux-libc-dev:i386
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - gcc-4.8-multilib
      - gcc-4.8-aarch64-linux-gnu
      - gcc-4.8-powerpc-linux-gnu
      - gcc-aarch64-linux-gnu
      - gcc-powerpc-linux-gnu
      - libc6-arm64-cross
      - libc6-powerpc-cross
      - libc6-dev-arm64-cross
      - libc6-dev-powerpc-cross
      - libglfw3-dev
      - libsdl2-dev
      - qemu

os:
    - linux

compiler:
    - gcc

script:
    - scripts/build.sh
    - (pushd player/; ./build.sh; popd)

after_success:
    - bash <(curl -s https://codecov.io/bash)
